# Way to send Telegram message with:
# "Normal" reposts with a normal message
# "Telegraph" reposts with in a Telegraph article
RepostWith: "telegraph"

# Telegram bot token
# Can be created using @BotFather
TelegramBotToken: ""

# Cooldown in seconds before checking for new posts
CheckCooldown: 3

# Telegraph article settings
# Matters if you use "Telegraph" in RepostWith option
Telegraph:
  AuthorShortName: "Reposter"
  AuthorName: "Vk to Telegram reposter"
  AuthorUrl: "https://github.com/oqo0"
  PageName: "NewPage"
  VkPostLinkMessage: "Original Vk post"

# Vk to Telegram reposters list
# Allows unlimited amount of reposters
# Example:
# 
# -
#   VkGroupId: "277978367"
#   VkGroupToken: "groupToken"
#   TelegramChannelId: "939729831"
#
Reposters:
  -
    VkGroupId: "0"
    VkGroupToken: ""
    TelegramChannelId: "0"
