# Way to send Telegram message with:
# "Message" reposts with a normal message
# "Telegraph" reposts with in a Telegraph article
RepostWith: "telegraph"

# Telegram bot token
# Can be created using @BotFather
TelegramBotToken: ""

# Vk to Telegram reposters list
# Allows unlimited amount of reposters
# Example:
# 
# -
#   VkGroupId: "277978367"
#   VkGroupToken: "groupToken"
#   TelegramChannelId: "939729831"
#
Reposters:
  -
    VkGroupId: "0"
    VkGroupToken: ""
    TelegramChannelId: "0"
